global:
  scrape_interval: 15s  # Intervalo de recolección de métricas

scrape_configs:
  - job_name: "hadoop"
    static_configs:
      - targets: ["namenode:9870", "yarnmaster:8088"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
