version: '3.1'

networks:
    hadoop-net:
        driver: bridge

services:

  namenode:
    build: ./NameNode
    image: hadoop-namenode-image-iabd12:latest
    container_name: namenode
    hostname: namenode
    command: /opt/bd/start-daemons.sh
    ports:
        - "9870:9870"
    networks:
        - hadoop-net
    volumes:
        - /c/Users/IABD12/Documents/GitHub/ClaseIABD/David:/home

  resourcemanager:
    build: ./ResourceManager
    image: hadoop-resourcemanager-image-iabd12:latest
    container_name: resourcemanager
    hostname: resourcemanager
    command: /opt/bd/start-daemons.sh
    ports:
        - "8088:8088"
    networks:
        - hadoop-net
    volumes:
        - /c/Users/IABD12/Documents/GitHub/ClaseIABD/David:/home

  dnnm:
    build: ./DataNode-NodeManager
    image: hadoop-datanode-image-iabd12:latest
    hostname: datanode
    container_name: datanode
    ports:
        - "9866:9866"
        - "9864:9864"
    depends_on:
        - namenode
        - resourcemanager
    command: /opt/bd/start-daemons.sh
    networks:
        - hadoop-net
    # volumes:
      #  - /c/Users/IABD12/Documents/GitHub/ClaseIABD/David:/home


