version: '3.1'

networks:
  hadoop-net:
    driver: bridge

services:
  namenode:
    build: ./NameNode
    image: hadoop-namenode-image-iabd12:latest
    container_name: namenode
    hostname: namenode
    command: /opt/bd/start-daemons.sh
    ports:
      - "9870:9870"   # Web UI de HDFS
      - "9000:9000"   # RPC del NameNode
    networks:
      - hadoop-net
    volumes:
      - /c/Users/IABD12/Documents/GitHub/ClaseIABD/David:/home  # Ruta montada

  resourcemanager:
    build: ./ResourceManager
    image: hadoop-resourcemanager-image-iabd12:latest
    container_name: resourcemanager
    hostname: resourcemanager
    command: /opt/bd/start-daemons.sh
    ports:
      - "8088:8088"   # Web UI del ResourceManager
    networks:
      - hadoop-net
    volumes:
      - /c/Users/IABD12/Documents/GitHub/ClaseIABD/David:/home  # Ruta montada

  dnnm:
    build: ./DataNode-NodeManager
    image: hadoop-datanode-image-iabd12:latest
    container_name: datanode
    hostname: datanode
    command: /opt/bd/start-daemons.sh
    ports:
      - "9866:9866"  # Web UI del DataNode
      - "9864:9864"  # Bloques de datos
    depends_on:
      - namenode
      - resourcemanager
    networks:
      - hadoop-net

  jupyter:
    build: ./Jupyter
    image: hadoop-jupyter-image-iabd12:latest
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8888:8888"  # Puerto para Jupyter Notebook
    networks:
      - hadoop-net
    volumes:
      - /c/Users/IABD12/Documents/GitHub/ClaseIABD/David:/opt/bd/jupyter-data  # Datos accesibles desde Jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"  # Activa JupyterLab
