networks:
  hadoop-net:
    driver: bridge

services:
  namenode:
    image: bigchuungus/hadoop-namenode-image-iabd12:v2.0
    container_name: namenode2
    hostname: namenode
    command: /opt/bd/start-daemons.sh
    ports:
      - "9870:9870"   
      - "9000:9000"   
    networks:
      - hadoop-net
    volumes:
      - "${USER_PATH}/Documents/GitHub/ClaseIABD/David:/home"  

  resourcemanager:
    image: bigchuungus/hadoop-resourcemanager-image-iabd12:v2.0
    container_name: resourcemanager2
    hostname: resourcemanager
    command: /opt/bd/start-daemons.sh
    ports:
      - "8088:8088"   
    networks:
      - hadoop-net
    volumes:
      - "${USER_PATH}/Documents/GitHub/ClaseIABD/David:/home"  

  dnnm:
    image: bigchuungus/hadoop-datanode-image-iabd12:v2.0
    container_name: datanode2
    hostname: datanode
    command: /opt/bd/start-daemons.sh
    ports:
      - "9866:9866"  
      - "9864:9864"  
    depends_on:
      - namenode
      - resourcemanager
    networks:
      - hadoop-net

  jupyter:
    image: bigchuungus/hadoop-jupyter-image-iabd12:v2.0
    container_name: jupyter2
    hostname: jupyter
    ports:
      - "8888:8888"  
    networks:
      - hadoop-net
    volumes:
      - "${USER_PATH}/Documents/GitHub/ClaseIABD/David:/opt/bd/jupyter-data"  
    environment:
      JUPYTER_ENABLE_LAB: "yes"  
